version: '3.8'

services:
  mtc-helper-bot:
    build:
      context: ..
      dockerfile: docker_files/Dockerfile
    container_name: mtc-helper-bot
    restart: unless-stopped
    environment:
      # Переменные окружения (добавьте свои)
      - PYTHONUNBUFFERED=1
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
    # Если нужен доступ к порту
    ports:
      - "8000:8000"
      - "80:80"
      - "443:443"
    # Если нужны переменные окружения из файла
    # env_file:
    #   - .env
